# General settings
nats_url: "nats-broker:4222"
d1_id: "1a86:7523"

# Refer to events/main.py for the following settings
events_targets:
- ["046d:c21f", "logitech_f710"]  # (id, device)

# Refer to events/publisher.py for the following settings
alive_gap: 0.1
queue_cap: 1024
